### ISSUE TITLE
Navigating back and forth the webpage displays empty webpage

### ISSUE THREAD

**Issue by noahweasley** [tezon22/ECE#127]
When I use my browser's back-and-forth keys, the previous page becomes empty, even though something was previously there

**Comment by Ryan-Zayne** [comment]
Yeah, it's been going on for a while...
Seems ou routing and fetching system still needs a bit more fine tuning.
It's nice you reminded us of this cuz we most probably forgot

**Comment by Eradz** [comment]
Its been fixed with better routing and fetching of data.
Thanks for bringing it to our notice
